import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/Navbar/Navbar";
import styles from "$app/App.module.scss";
import classNames from "classnames/bind";
import NavbarSearch from "~/components/Navbar/NavbarSearch";

const inter = Inter({ subsets: ["latin"] });
const cx = classNames.bind(styles);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={cx("boss")}>
          <nav>
            <NavbarSearch />

            <Navbar />
          </nav>
          <div className={cx("body")}>{children}</div>
        </div>
      </body>
    </html>
  );
}
