import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import styles from "$app/App.module.scss";
import classNames from "classnames/bind";

import IntlProviderWrapper from "~/utility/Language/IntlProviderWrapper";
import ReduxProvider from "~/redux/ReduxProvider";
import ThemeProviderWrapper from "~/utility/Themes/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });
const cx = classNames.bind(styles);
export const metadata: Metadata = {
  title: "ABC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={cx("boss")}>
          <ReduxProvider>
            <ThemeProviderWrapper>
              <div className={cx("body")}>
                <IntlProviderWrapper>{children}</IntlProviderWrapper>
              </div>
            </ThemeProviderWrapper>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
