import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/Navbar/Navbar";
import styles from "$app/App.module.scss";
import classNames from "classnames/bind";
import NavbarSearch from "~/components/Navbar/NavbarSearch";
import IntlProviderWrapper from "~/utility/Language/IntlProviderWrapper";
import ReduxProvider from "~/redux/ReduxProvider";
import ThemeProviderWrapper from "~/utility/Themes/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });
const cx = classNames.bind(styles);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <div className={cx("boss")}>
            <ThemeProviderWrapper>
              <IntlProviderWrapper>
                <nav>
                  <NavbarSearch />

                  <Navbar />
                </nav>
                <div className={cx("body")}>{children}</div>
              </IntlProviderWrapper>
            </ThemeProviderWrapper>
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
